# Generated by Django 5.2.1 on 2025-05-20 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('error', '错误')], default='success', max_length=20, verbose_name='结果状态')),
                ('result_data', models.JSONField(default=dict, verbose_name='结果数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务结果',
                'verbose_name_plural': '任务结果',
            },
        ),
    ]
