# Generated by Django 5.2.1 on 2025-06-01 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200, verbose_name='产品ID')),
                ('version_name', models.CharField(max_length=200, verbose_name='版本名称')),
                ('version_description', models.TextField(blank=True, verbose_name='版本描述')),
                ('version_created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('version_updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本',
                'ordering': ['-version_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.CharField(max_length=200, verbose_name='仓库URL')),
                ('repo_revision', models.CharField(max_length=200, verbose_name='仓库版本')),
                ('manifest_file', models.FileField(upload_to='manifests/', verbose_name='清单文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='api.version', verbose_name='版本')),
            ],
            options={
                'verbose_name': '清单',
                'verbose_name_plural': '清单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='版本配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.version', verbose_name='版本')),
            ],
            options={
                'verbose_name': '版本配置',
                'verbose_name_plural': '版本配置',
                'ordering': ['-created_at'],
            },
        ),
    ]
