# Generated by Django 5.2.1 on 2025-06-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_version_manifest_versionconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='manifest_file',
        ),
        migrations.AddField(
            model_name='manifest',
            name='manifest_filepath',
            field=models.CharField(default='', max_length=200, verbose_name='清单文件路径'),
            preserve_default=False,
        ),
    ]
